1 compatibility problem Advanced Java Folding 2 (Fork) 761.678.268-canary is binary incompatible with IntelliJ IDEA Ultimate IU-233.15619.7 due to the following problem Method not found (1) Invocation of unresolved method ServicesKt.serviceNotFoundError(...) (1) Method FoldingService.clearAllKeys(Project) contains an invokestatic instruction referencing an unresolved method ServicesKt.serviceNotFoundError(...). This can lead to NoSuchMethodError exception at runtime.